import { NextRequest } from "next/server";
import { getClient } from "@/lib/copilot-client";
import { getSessionOptions, enhanceModelError } from "@/lib/model-config";
import { GitHubService } from "@/lib/github-service";
import type { GeneratedFile } from "@/lib/github-service";

const PRONGHORN_SYSTEM_CONTEXT = `You are Pronghorn, an enterprise application generator built for the Government of Alberta.
Your job is to generate complete, production-ready project files based on user requirements.

CRITICAL INSTRUCTIONS:
- Output ONLY valid JSON. No markdown fences, no extra text.
- Use this exact format:
{
  "description": "Brief one-line project description",
  "files": [
    { "path": "relative/path/to/file", "content": "full file content" }
  ]
}
- Generate a complete, working project with all necessary files
- Always include: package.json (or equivalent), README.md, .gitignore, source code files
- Follow enterprise standards: proper error handling, input validation, security headers
- Use TypeScript for Node.js projects, type hints for Python projects
- Include health check endpoints for web services
- Add CORS support for APIs
- Include basic tests when appropriate`;

interface SummarizeSession {
  sendAndWait(
    msg: { prompt: string },
    timeout: number
  ): Promise<{ data?: unknown } | undefined>;
  destroy(): Promise<void>;
}

interface GeneratedProject {
  description: string;
  files: GeneratedFile[];
}

function extractJSON(text: string): string {
  const codeBlockMatch = text.match(/```(?:json)?\s*\n?([\s\S]*?)\n?```/);
  if (codeBlockMatch) return codeBlockMatch[1].trim();
  const jsonMatch = text.match(/\{[\s\S]*\}/);
  if (jsonMatch) return jsonMatch[0];
  return text;
}

function parseGeneratedProject(content: string): GeneratedProject {
  const jsonStr = extractJSON(content);
  const parsed = JSON.parse(jsonStr);
  if (!parsed.files || !Array.isArray(parsed.files)) {
    throw new Error("Invalid response: missing 'files' array");
  }
  const files: GeneratedFile[] = parsed.files
    .filter((f: Record<string, unknown>) => f.path && f.content)
    .map((f: Record<string, unknown>) => ({
      path: String(f.path),
      content: String(f.content),
    }));
  if (files.length === 0) {
    throw new Error("No valid files generated");
  }
  return {
    description: String(parsed.description || "Generated by Pronghorn"),
    files,
  };
}

function sendSSE(
  controller: ReadableStreamDefaultController,
  encoder: TextEncoder,
  data: Record<string, unknown>
) {
  controller.enqueue(encoder.encode(`data: ${JSON.stringify(data)}\n\n`));
}

export async function POST(req: NextRequest) {
  const body = await req.json();
  const { requirements, appName } = body as {
    requirements?: string;
    appName?: string;
  };

  if (!requirements || typeof requirements !== "string" || !requirements.trim()) {
    return new Response(
      JSON.stringify({ error: "Missing or empty 'requirements' field" }),
      { status: 400, headers: { "Content-Type": "application/json" } }
    );
  }
  if (!appName || typeof appName !== "string" || !appName.trim()) {
    return new Response(
      JSON.stringify({ error: "Missing or empty 'appName' field" }),
      { status: 400, headers: { "Content-Type": "application/json" } }
    );
  }

  const sandboxOrg = process.env.PRONGHORN_SANDBOX_ORG;
  const ghToken = process.env.PRONGHORN_GITHUB_TOKEN || process.env.GITHUB_TOKEN;

  if (!sandboxOrg) {
    return new Response(
      JSON.stringify({ error: "PRONGHORN_SANDBOX_ORG not configured" }),
      { status: 500, headers: { "Content-Type": "application/json" } }
    );
  }
  if (!ghToken) {
    return new Response(
      JSON.stringify({ error: "GitHub token not configured" }),
      { status: 500, headers: { "Content-Type": "application/json" } }
    );
  }

  const encoder = new TextEncoder();
  const stream = new ReadableStream({
    async start(controller) {
      let session: SummarizeSession | null = null;

      try {
        // Stage 1
        sendSSE(controller, encoder, {
          stage: "analyzing",
          message: "🔍 Analyzing requirements...",
          progress: 10,
        });

        const copilot = await getClient();
        const options = await getSessionOptions();
        session = (await copilot.createSession(
          options
        )) as unknown as SummarizeSession;

        // Stage 2
        sendSSE(controller, encoder, {
          stage: "generating",
          message: "⚡ Generating project with Copilot SDK...",
          progress: 25,
        });

        const prompt = `${PRONGHORN_SYSTEM_CONTEXT}\n\nGenerate a complete project for:\nApplication Name: ${appName}\nRequirements: ${requirements}\n\nRemember: Output ONLY valid JSON with "description" and "files" array.`;

        const response = await session.sendAndWait({ prompt }, 180_000);
        const content =
          (response?.data as { content?: string })?.content ?? "";
        if (!content) throw new Error("Empty response from Copilot SDK");

        // Stage 3
        sendSSE(controller, encoder, {
          stage: "parsing",
          message: "📦 Parsing generated project files...",
          progress: 50,
        });

        const project = parseGeneratedProject(content);

        sendSSE(controller, encoder, {
          stage: "parsed",
          message: `📄 Generated ${project.files.length} files`,
          progress: 55,
          fileCount: project.files.length,
          filePaths: project.files.map((f) => f.path),
        });

        // Stage 4
        sendSSE(controller, encoder, {
          stage: "creating_repo",
          message: `🏗️ Creating repository in ${sandboxOrg}...`,
          progress: 60,
        });

        const githubService = new GitHubService(ghToken, sandboxOrg);
        const repoUrl = await githubService.createRepo(
          appName,
          `${project.description} — Generated by Pronghorn`
        );

        sendSSE(controller, encoder, {
          stage: "repo_created",
          message: `✅ Repository created: ${repoUrl}`,
          progress: 70,
          repoUrl,
        });

        // Stage 5
        sendSSE(controller, encoder, {
          stage: "pushing_code",
          message: `📤 Pushing ${project.files.length} files...`,
          progress: 80,
        });

        const filesCreated = await githubService.pushFiles(
          appName,
          project.files,
          "feat: initial project scaffold generated by Pronghorn\n\nGenerated from requirements using GitHub Copilot SDK"
        );

        sendSSE(controller, encoder, {
          stage: "code_pushed",
          message: `✅ ${filesCreated} files committed to main`,
          progress: 85,
        });

        // Stage 6
        sendSSE(controller, encoder, {
          stage: "configuring_security",
          message: "🔒 Configuring security policies...",
          progress: 90,
        });

        const securityActions =
          await githubService.configureSecurity(appName);

        sendSSE(controller, encoder, {
          stage: "security_configured",
          message: `🛡️ Security: ${securityActions.length} policies applied`,
          progress: 95,
          securityActions,
        });

        // Stage 7
        sendSSE(controller, encoder, {
          stage: "complete",
          message: "🎉 Project generated and deployed successfully!",
          progress: 100,
          repoUrl,
          filesCreated,
          description: project.description,
          securityActions,
        });

        controller.enqueue(encoder.encode("data: [DONE]\n\n"));
        controller.close();
      } catch (err) {
        const enhanced = enhanceModelError(err);
        sendSSE(controller, encoder, {
          stage: "error",
          message: `❌ Error: ${enhanced.message}`,
          error: enhanced.message,
        });
        controller.close();
      } finally {
        await session?.destroy();
      }
    },
  });

  return new Response(stream, {
    headers: {
      "Content-Type": "text/event-stream",
      "Cache-Control": "no-cache",
      Connection: "keep-alive",
    },
  });
}
